In [2]:
#whether this way of getting the x and y coordinate works
location=participant.get_transform().location
x=location[0]
z=location[2]
print(x,z)

NameError: name 'participant' is not defined

In [9]:
participants_positions= [[0,35,2,23,43,23,4,5],[1,35,2,23,43,23,4,5]]
past = np.array([[0,35,2,23,43,23,4,5],[1,35,2,23,43,23,4,5],[2,35,2,23,43,23,4,5],[3,35,2,23,43,23,4,5],[3,35,2,23,43,23,4,5]])

In [23]:
import numpy as np
participants=["car",'car','pedestrian','car']
new_coords=np.zeros([len(participants)*2])


for p in range(len(participants)):
    new_coords[2*p],new_coords[2*p+1]= get_new_positions(p)
past= np.vstack((past,new_coords))
past= np.delete(past,0,0)

# for p in range(len(participants)):
#     #nput = torch.tensor(past[p*2:p*2+1,:])
#     pred = [8,6] #= model_load.prediction(rnn_model,input,future_timesegments)
#     pred.detach().numpy().prepend(participants_positions[2*p:2*p+1,:])

print(past)

22
94
61
54
[[57. 58. 90. 91. 39. 40. 77. 78.]
 [72. 73.  8.  9. 51. 52. 15. 16.]
 [29. 30. 44. 45. 92. 93.  2.  3.]
 [ 2.  3. 69. 70. 74. 75. 41. 42.]
 [22. 23. 94. 95. 61. 62. 54. 55.]]


In [5]:
import random
def get_new_positions(p):
    i=round(100*random.random())
    print(i)
    return i,i+1

In [4]:
import matplotlib.pyplot as plt

depth_data=plt.imread('Rubens_test_files/Pictures/depth_camera_Sun_Apr_14_20_33_08_2024.png') #to get the data as an array
segment_data=plt.imread('Rubens_test_files/Pictures/instance_camera_Sun_Apr_14_20_33_08_2024.png') #to get the data as an array

depth_data=convert_image_to_depth(depth_data)
segment_data=np.round(segment_data*255)
labels=segment_data[:,:,0]

depth_Width=depth_data[1,:,0].size()

NameError: name 'np' is not defined

In [23]:
import carla
client = carla.Client('localhost', 2000)
world = client.get_world()

actor_list = world.get_actors()
for a in actor_list:
    if a.id>146:
        a.destroy()

Actor(id=152, type=vehicle.ford.ambulance)
Actor(id=151, type=vehicle.audi.a2)
Actor(id=150, type=vehicle.toyota.prius)
