In [3]:
#whether this way of getting the x and y coordinate works
location=participant.get_transform().location
x=location[0]
z=location[2]
print(x,z)

NameError: name 'participant' is not defined

In [64]:
participants_positions= [[0,35,2,23,43,23,4,5],[1,35,2,23,43,23,4,5]]
past = np.array([[0,35,2,23,43,23,4,5],[1,35,2,23,43,23,4,5],[2,35,2,23,43,23,4,5],[3,35,2,23,43,23,4,5],[3,35,2,23,43,23,4,5]])

In [101]:
import numpy as np
participants=["car",'car','pedestrian','car']
new_coords=np.zeros([len(participants)*2])


for p in range(len(participants)):
    new_coords[2*p],new_coords[2*p+1]=get_new_positions(p)
past= np.vstack((new_coords,past))
past=np.delete(past,5,0) 

# for p in range(len(participants)):
#     #nput = torch.tensor(past[p*2:p*2+1,:])
#     pred = [8,6] #= model_load.prediction(rnn_model,input,future_timesegments)
#     pred.detach().numpy().prepend(participants_positions[2*p:2*p+1,:])

print(past)

28
15
88
68
[[28. 29. 15. 16. 88. 89. 68. 69.]
 [49. 50. 91. 92. 94. 95. 64. 65.]
 [36. 37. 57. 58. 51. 52. 67. 68.]
 [89. 90. 22. 23. 12. 13. 28. 29.]
 [92. 93. 94. 95. 35. 36. 16. 17.]]


In [55]:
import random
def get_new_positions(p):
    i=round(100*random.random())
    print(i)
    return i,i+1
